import yogurt from "./assets/yogurt.png";
import banana from "./assets/banana.png";
import strawberry from "./assets/strawberry.png";
import blueberry from "./assets/blueberry.png";

export const data = [
  {
    id: 1,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "produce",
  },
  {
    id: 2,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "produce",
  },
  {
    id: 3,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "produce",
  },
  {
    id: 4,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "produce",
  },
  {
    id: 5,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "produce",
  },
  {
    id: 6,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "produce",
  },
  {
    id: 7,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "produce",
  },
  {
    id: 8,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "produce",
  },
  {
    id: 9,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "prepared-foods",
  },
  {
    id: 10,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "prepared-foods",
  },
  {
    id: 11,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "prepared-foods",
  },
  {
    id: 12,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "prepared-foods",
  },
  {
    id: 13,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "prepared-foods",
  },
  {
    id: 14,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "prepared-foods",
  },
  {
    id: 15,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "prepared-foods",
  },
  {
    id: 16,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "prepared-foods",
  },
  {
    id: 17,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "canned-foods-soups",
  },
  {
    id: 18,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "canned-foods-soups",
  },
  {
    id: 19,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "canned-foods-soups",
  },
  {
    id: 20,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "canned-foods-soups",
  },
  {
    id: 21,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "canned-foods-soups",
  },
  {
    id: 22,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "canned-foods-soups",
  },
  {
    id: 23,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "canned-foods-soups",
  },
  {
    id: 24,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "canned-foods-soups",
  },
  {
    id: 25,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "bakery",
  },
  {
    id: 26,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "bakery",
  },
  {
    id: 27,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "bakery",
  },
  {
    id: 28,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "bakery",
  },
  {
    id: 29,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "bakery",
  },
  {
    id: 30,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "bakery",
  },
  {
    id: 31,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "bakery",
  },
  {
    id: 32,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "bakery",
  },
  {
    id: 33,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "diary-eggs",
  },
  {
    id: 34,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "diary-eggs",
  },
  {
    id: 35,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "diary-eggs",
  },
  {
    id: 36,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "diary-eggs",
  },
  {
    id: 37,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "diary-eggs",
  },
  {
    id: 38,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "diary-eggs",
  },
  {
    id: 39,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "diary-eggs",
  },
  {
    id: 40,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "diary-eggs",
  },
  {
    id: 41,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "meat-seafood",
  },
  {
    id: 42,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "meat-seafood",
  },
  {
    id: 43,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "meat-seafood",
  },
  {
    id: 44,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "meat-seafood",
  },
  {
    id: 45,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "meat-seafood",
  },
  {
    id: 46,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "meat-seafood",
  },
  {
    id: 47,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "meat-seafood",
  },
  {
    id: 48,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "meat-seafood",
  },
  {
    id: 49,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "frozen",
  },
  {
    id: 50,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "frozen",
  },
  {
    id: 51,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "frozen",
  },
  {
    id: 52,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "frozen",
  },
  {
    id: 53,
    img: strawberry,
    price: 0.69,
    name: "Strawberries",
    weight: "1 lb",
    category: "frozen",
  },
  {
    id: 54,
    img: yogurt,
    price: 0.69,
    name: "Yogurt",
    weight: "1 lb",
    category: "frozen",
  },
  {
    id: 55,
    img: banana,
    price: 0.69,
    name: "Banana 1 ct",
    weight: "18 oz",
    category: "frozen",
  },
  {
    id: 56,
    img: blueberry,
    price: 0.69,
    name: "Blackberries",
    weight: "1 lb",
    category: "frozen",
  },
];
